services:
  - type: web
    name: projects-app-backend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start:prod
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 3000 